services:
    _defaults:
        autowire: true
        public: false
        autoconfigure: true

    Lle\CruditPlatformBundle\Service\FrontMenuCredentialWarmup:
        tags:
          - name: credential.warmup
            priority: 20
    Lle\CruditPlatformBundle\Service\CruditCredentialWarmup:
        tags:
          - name: credential.warmup
            priority: 20
    Lle\CruditPlatformBundle\Service\WidgetCredentialWarmup:
        tags:
          - name: credential.warmup
            priority: 20
    Lle\CruditPlatformBundle\Service\WorkflowCredentialWarmup:
        tags:
          - name: credential.warmup
            priority: 20
